artists:
  year12:
    en:
      - url-name: andras-wolsky
        name: andrás wolsky
      - url-name: angela-thomas
        name: angela thomas
      - url-name: barna-benedek
        name: barna benedek
      - url-name: bruno-haas
        name: bruno haas
      - url-name: dora-maurer
        name: dóra maurer
      - url-name: erich-schmid
        name: erich schmid
      - url-name: georgi-dimitrov
        name: georgi dimitrov
      - url-name: georgi-yanakiev
        name: georgi yanakiev
      - url-name: guido-winkler
        name: guido winkler
      - url-name: jose-heerkens
        name: josé heerkens
      - url-name: maria-chakarova
        name: maria chakarova
      - url-name: nikolay-diulgheroff
        name: nikolay diulgheroff
      - url-name: richard-van-der-aa
        name: richard van der aa
      - url-name: tibor-gayor
        name: tibor gáyor
    bg:
      - url-name: angela-thomas
        name: ангела томас
      - url-name: andras-wolsky
        name: андраш волски
      - url-name: barna-benedek
        name: барна бенедек
      - url-name: bruno-haas
        name: бруно хаас
      - url-name: georgi-dimitrov
        name: георги димитров
      - url-name: georgi-yanakiev
        name: георги янакиев
      - url-name: dora-maurer
        name: дора маурер
      - url-name: erich-schmid
        name: ерих шмид
      - url-name: jose-heerkens
        name: йозе хееркенс
      - url-name: guido-winkler
        name: гидо винклер
      - url-name: maria-chakarova
        name: мария чакърова
      - url-name: nikolay-diulgheroff
        name: николай дюлгеров
      - url-name: richard-van-der-aa
        name: ричард ван дер аа
      - url-name: tibor-gayor
        name: тибор гайор
  year14:
    en:
      - url-name: anna-maria-bogner
        name: anna-maria bogner
      - url-name: arjan-janssen
        name: arjan janssen
      - url-name: bob-bonies
        name: bob bonies
      - url-name: bruno-haas
        name: bruno haas
      - url-name: georgi-dimitrov
        name: georgi dimitrov
      - url-name: guillaume-millet
        name: guillaume millet
      - url-name: krasimira-stikar
        name: krasimira stikar
      - url-name: maria-chakarova
        name: maria chakarova
      - url-name: max-bill
        name: max bill
      - url-name: simon-ingram
        name: simon ingram
      - url-name: theodore-markoglou
        name: theodore markoglou
      - url-name: yorgos-vourlidas
        name: yorgos vourlidas
    bg:
      - url-name: anna-maria-bogner
        name: анна-мария богнер
      - url-name: arjan-janssen
        name: арян янсен
      - url-name: bob-bonies
        name: боб бонис
      - url-name: bruno-haas
        name: бруно хаас
      - url-name: georgi-dimitrov
        name: георги димитров
      - url-name: guillaume-millet
        name: гийом мийе
      - url-name: yorgos-vourlidas
        name: йоргос вурлидас
      - url-name: krasimira-stikar
        name: красимира стикар
      - url-name: max-bill
        name: макс бил
      - url-name: maria-chakarova
        name: мария чакърова
      - url-name: simon-ingram
        name: саймън инграм
      - url-name: theodore-markoglou
        name: тодорис маркоглу

